# Generated by Django 5.2.11 on 2026-02-09 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField()),
                ('widht', models.IntegerField()),
                ('height', models.IntegerField()),
                ('url', models.CharField(max_length=250)),
                ('avg_color', models.CharField(max_length=32)),
                ('alt', models.CharField(max_length=250)),
                ('Photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=250)),
                ('original_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='photos.photo')),
            ],
        ),
    ]
