# Generated by Django 5.2.11 on 2026-02-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Photographer',
            new_name='photographer',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='widht',
            new_name='width',
        ),
    ]
