# Generated by Django 5.2.11 on 2026-02-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_photographer_photo_photographer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='external_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='photovariant',
            name='url',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
